name: CD
 
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master, develop
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Install Dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'
    - run: composer install --no-dev --optimize-autoloader
 
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**