name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
  
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
      php-version: '8.2.12'
    - run: composer install
    - run: php bin/phpunit